openapi: 3.0.0
info:
  title: Bank Statement Analyzer
  version: 1.0.0
paths:
  /analyze:
    post:
      summary: Analyze uploaded bank PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully analyzed
          content:
            application/json:
              schema:
                type: object
