openapi: 3.1.0
info:
  title: Bank Statement Analyzer
  version: 1.0.0
servers:
  - url: https://mca-analyzer.up.railway.app
paths:
  /analyze:
    post:
      operationId: analyzeBankStatement
      summary: Analyze uploaded bank PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully analyzed
          content:
            application/json:
              schema:
                type: object
                properties:
                  bank:
                    type: string
                  monthly_deposits:
                    type: number
                  monthly_withdrawals:
                    type: number
                  average_balance:
                    type: number
                  ending_balance:
                    type: number
                  nsf_count:
                    type: integer
                  low_balance_days:
                    type: integer
                  daily_balances:
                    type: array
                    items:
                      type: number
